# 0. Eleccion del dataset


link del dataset https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset/data

## Predicción de ictus mediante inteligencia artificial

He elegido este dataset sobre la predicción de ictus porque según la Organización Mundial de la Salud esta enfermedad es la segunda causa de muerte en el planeta y representa el 11 por ciento de los fallecimientos totales.

El objetivo principal de mi trabajo es usar esta información para crear un modelo de inteligencia artificial capaz de identificar a pacientes con riesgo de sufrir un infarto cerebral.

### Descripción del conjunto de datos

El conjunto de datos incluye información de los pacientes repartida en las siguientes categorías:

#### Información personal
Incluye datos como el género, la edad, el estado civil, el tipo de trabajo y si la persona vive en una zona rural o urbana.

#### Historial clínico
Sirve para saber si el paciente padece hipertensión o alguna enfermedad del corazón.

#### Datos de salud actuales
Aquí se incluyen el nivel de glucosa en sangre, el índice de masa corporal y si la persona fuma o ha fumado anteriormente.

#### Resultado
La variable objetivo se llama stroke y marca con un 1 si el paciente ha tenido un ictus o con un 0 si no lo ha tenido.

Este dataset permite analizar distintos factores de riesgo y es adecuado para entrenar un modelo predictivo aplicado al ámbito de la salud.

# 1. Preparacion de los datos

In [31]:
import pandas as pd

In [32]:
#Cargamos el dataset
df = pd.read_csv('./datasets/healthcare-dataset-stroke-data.csv')
# y vemos su tamaño y sus primeras filas
print(len(df))
df.head().T

5110


0              1             2        3  \
id                            9046          51676         31112    60182   
gender                        Male         Female          Male   Female   
age                           67.0           61.0          80.0     49.0   
hypertension                     0              0             0        0   
heart_disease                    1              0             1        0   
ever_married                   Yes            Yes           Yes      Yes   
work_type                  Private  Self-employed       Private  Private   
Residence_type               Urban          Rural         Rural    Urban   
avg_glucose_level           228.69         202.21        105.92   171.23   
bmi                           36.6            NaN          32.5     34.4   
smoking_status     formerly smoked   never smoked  never smoked   smokes   
stroke                           1              1             1        1   

                               4  
id                          1665  
gender                    Female  
age                         79.0  
hypertension                   1  
heart_disease                  0  
ever_married                 Yes  
work_type          Self-employed  
Residence_type             Rural  
avg_glucose_level         174.12  
bmi                         24.0  
smoking_status      never smoked  
stroke                         1

In [33]:
df.dtypes


id                     int64
gender                object
age                  float64
hypertension           int64
heart_disease          int64
ever_married          object
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke                 int64
dtype: object

Como todos los tipos de datos estan con su tipo no haria falta hacer ningun cambio 

In [34]:
# Información básica del DataFrame para ver tipos de datos y valores nulos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5110 non-null   int64  
 1   gender             5110 non-null   object 
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64  
 4   heart_disease      5110 non-null   int64  
 5   ever_married       5110 non-null   object 
 6   work_type          5110 non-null   object 
 7   Residence_type     5110 non-null   object 
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object 
 11  stroke             5110 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB


In [35]:
# Como podemos ver en la columna 'bmi' hay valores nulos
df['bmi'].isnull().sum()
# Vemos las filas con valores nulos en la columna 'bmi'
df[df['bmi'].isnull()]


id  gender   age  hypertension  heart_disease ever_married  \
1     51676  Female  61.0             0              0          Yes   
8     27419  Female  59.0             0              0          Yes   
13     8213    Male  78.0             0              1          Yes   
19    25226    Male  57.0             0              1           No   
27    61843    Male  58.0             0              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5039  42007    Male  41.0             0              0           No   
5048  28788    Male  40.0             0              0          Yes   
5093  32235  Female  45.0             1              0          Yes   
5099   7293    Male  40.0             0              0          Yes   
5105  18234  Female  80.0             1              0          Yes   

          work_type Residence_type  avg_glucose_level  bmi   smoking_status  \
1     Self-employed          Rural             202.21  NaN     never smoked   
8           Private          Rural              76.15  NaN          Unknown   
13          Private          Urban             219.84  NaN          Unknown   
19         Govt_job          Urban             217.08  NaN          Unknown   
27          Private          Rural             189.84  NaN          Unknown   
...             ...            ...                ...  ...              ...   
5039        Private          Rural              70.15  NaN  formerly smoked   
5048        Private          Urban             191.15  NaN           smokes   
5093       Govt_job          Rural              95.02  NaN           smokes   
5099        Private          Rural              83.94  NaN           smokes   
5105        Private          Urban              83.75  NaN     never smoked   

      stroke  
1          1  
8          1  
13         1  
19         1  
27         1  
...      ...  
5039       0  
5048       0  
5093       0  
5099       0  
5105       0  

[201 rows x 12 columns]

In [36]:
# y las remplazamos por la mediana de la columna para no afectar la distribución
df['bmi'] = df['bmi'].fillna(df['bmi'].median())
# Verificamos que ya no haya valores nulos en la columna 'bmi'
df['bmi'].isnull().sum()

np.int64(0)

In [37]:
# Ahora vamos a normalizar los valores de texto
# normalizar los valores de texto de los nombres de las columnas
df.columns = df.columns.str.lower().str.replace(' ', '_')
# Normalizamos los valores de texto en todo el dataset
replacer = lambda s: s.lower().str.replace(' ', '_')
for col in df.select_dtypes(include='object').columns:
    df[col] = replacer(df[col].str)
df.head().T

0              1             2        3  \
id                            9046          51676         31112    60182   
gender                        male         female          male   female   
age                           67.0           61.0          80.0     49.0   
hypertension                     0              0             0        0   
heart_disease                    1              0             1        0   
ever_married                   yes            yes           yes      yes   
work_type                  private  self-employed       private  private   
residence_type               urban          rural         rural    urban   
avg_glucose_level           228.69         202.21        105.92   171.23   
bmi                           36.6           28.1          32.5     34.4   
smoking_status     formerly_smoked   never_smoked  never_smoked   smokes   
stroke                           1              1             1        1   

                               4  
id                          1665  
gender                    female  
age                         79.0  
hypertension                   1  
heart_disease                  0  
ever_married                 yes  
work_type          self-employed  
residence_type             rural  
avg_glucose_level         174.12  
bmi                         24.0  
smoking_status      never_smoked  
stroke                         1

In [38]:
#Vamos a ver el numero de valores unicos por columna
categorical = [
    'gender', 
    'ever_married', 
    'work_type', 
    'residence_type', 
    'smoking_status', 
    'hypertension', 
    'heart_disease'
]
numerical = [
    'age', 
    'avg_glucose_level', 
    'bmi'
]
df[categorical].nunique()

gender            3
ever_married      2
work_type         5
residence_type    2
smoking_status    4
hypertension      2
heart_disease     2
dtype: int64

In [39]:
#Ahora con todo preparado vamos a separar los datos
from sklearn.model_selection import train_test_split
#Dividimos en entrenamiento y testn es train full ya que despues se sacara validacion
df_train_full , df_test = train_test_split(df, test_size=0.2, random_state=1)

# Dividimos en entrenamiento y validacion
df_train , df_val = train_test_split(df_train_full, test_size=0.33, random_state=1)

# Guardammos las etiquetas de los ejemplos en una variable
y_train = df_train.stroke.values
y_val = df_val.stroke.values
y_test = df_test.stroke.values

# Eliminamos la columna de etiquetas de los datos
del df_train['stroke']
del df_val['stroke']
del df_test['stroke']

In [40]:
# Vemos el tamaño de las particiones
print(len(df_train) ,len(y_train), 'train examples')
print(len(df_val),len(y_val), 'validation examples')
print(len(df_test), len(y_test), 'test examples')

2738 2738 train examples
1350 1350 validation examples
1022 1022 test examples


# 2. Análisis de importancia de prioridades


In [41]:
# Calculamos la media global de las personas que han tenido un ictus
global_mean = df_train_full.stroke.mean()
print(f'Media global de ictus: {round(global_mean, 3)}')

Media global de ictus: 0.046


Vemos que esuna enfermedad poco frecuente , lo que hace que el reto de la IA sea encontrar los patrones específicos que distinguen a ese pequeño grupo del resto ya que solo un 4,6% padecen de esta. Tambien como ya sabemos que hay pocos implica que una precisión alta puede ser engañosa porque el modelo podría acertar casi siempre simplemente prediciendo que nadie tendrá un ictus

In [42]:
#Vamos a ver si el genero influye en la media de ictus
female_mean = df_train_full[df_train_full.gender == 'female'].stroke.mean()
print(f'Riesgo en mujeres: {round(female_mean, 3)}')

male_mean = df_train_full[df_train_full.gender == 'male'].stroke.mean()
print(f'Riesgo en hombres: {round(male_mean, 3)}')

Riesgo en mujeres: 0.048
Riesgo en hombres: 0.044


En mi análisis el riesgo de sufrir un ictus es muy similar entre ambos sexos aunque las mujeres presentan una probabilidad ligeramente superior del 4.8% frente al 4.4% de los hombres. Esto indica que el género no es el factor más determinante de mi modelo pero sigue siendo una variable importante para realizar una predicción precisa.

In [43]:
# Vamos a ver tambien si el estado de fumador influye en la media de ictus
never_mean = df_train_full[df_train_full.smoking_status == 'never_smoked'].stroke.mean()
print(f'Riesgo nunca han fumado: {round(never_mean, 3)}')

smokes_mean = df_train_full[df_train_full.smoking_status == 'smokes'].stroke.mean()
print(f'Riesgo fumadores actuales: {round(smokes_mean, 3)}')

formerly_mean = df_train_full[df_train_full.smoking_status == 'formerly_smoked'].stroke.mean()
print(f'Riesgo ex-fumadores: {round(formerly_mean, 3)}')

Riesgo nunca han fumado: 0.047
Riesgo fumadores actuales: 0.046
Riesgo ex-fumadores: 0.072


Sobre el tabaquismo destaca que los ex-fumadores tienen el riesgo más alto con un 7.2% superando notablemente a quienes fuman actualmente o nunca lo han hecho. Estos resultados sugieren que el daño acumulado o el historial previo de tabaquismo es un factor de riesgo mucho más crítico en mi dataset que el hábito actual.

In [44]:
from sklearn.metrics import mutual_info_score
# Calculo de la informacion mutua para cada variable categorica 
# la correlaccion que tiene la variable objetivo con cada variable 
# , solo para categoricas , si es 0 no tiene relacion y mientras mas alto mas relacion 
calculate_mi = lambda col: mutual_info_score(col, df_train_full.stroke)

df_mi = df_train_full[categorical].apply(calculate_mi)
df_mi = df_mi.sort_values(ascending=False).to_frame(name='MI')
df_mi

MI
work_type       0.006146
hypertension    0.005674
heart_disease   0.005653
ever_married    0.004960
smoking_status  0.002092
residence_type  0.000171
gender          0.000045

El análisis de la información mutua nos muestra que la mas determinante es el tipo de trabajo , seguido de la hipertensión y de los infartos , el genero o la residencia son variables que no aportan mucho a si va a sufrir un ictus o no .

In [45]:
# Calculo de la correlacion para las variables numericas (coeficiente de correlacion de Pearson)
print(df_train_full[numerical].corrwith(df_train_full.stroke))

age                  0.235947
avg_glucose_level    0.117430
bmi                  0.035747
dtype: float64


Este análisis de correlación de Pearson muestra que la edad es el factor numérico más influyente ya que presenta la relación positiva más fuerte con el riesgo de ictus. El nivel de glucosa también aporta información relevante para el modelo mientras que el índice de masa corporal tiene el impacto más bajo de los tres valores analizados. Esto confirma que en mi dataset el riesgo de sufrir un infarto aumenta principalmente a medida que los pacientes envejecen y tienen niveles altos de azúcar.

In [46]:
# Riesgo de ictus según rangos de EDAD
print("Riesgo por edad (Jóvenes <= 30):")
print(round(df_train_full[df_train_full.age <= 30].stroke.mean(), 3))

print("Riesgo por edad (Adultos 31-60):")
print(round(df_train_full[(df_train_full.age > 30) & (df_train_full.age <= 60)].stroke.mean(), 3))

print("Riesgo por edad (Mayores > 60):")
print(round(df_train_full[df_train_full.age > 60].stroke.mean(), 3))

# Riesgo de ictus según rangos de GLUCOSA
print("\nRiesgo por glucosa (Normal <= 100):")
print(round(df_train_full[df_train_full.avg_glucose_level <= 100].stroke.mean(), 3))

print("Riesgo por glucosa (Moderada 101-150):")
print(round(df_train_full[(df_train_full.avg_glucose_level > 100) & (df_train_full.avg_glucose_level <= 150)].stroke.mean(), 3))

print("Riesgo por glucosa (Alta > 150):")
print(round(df_train_full[df_train_full.avg_glucose_level > 150].stroke.mean(), 3))

Riesgo por edad (Jóvenes <= 30):
0.002
Riesgo por edad (Adultos 31-60):
0.03
Riesgo por edad (Mayores > 60):
0.128

Riesgo por glucosa (Normal <= 100):
0.035
Riesgo por glucosa (Moderada 101-150):
0.034
Riesgo por glucosa (Alta > 150):
0.114


Esto confirma lo visto en la correlaccion , la edad y el azucar en sangre son los predictores mas potentes 

# 3. Ingenieria de prioridades

In [47]:
# lo pasamos a un diccionario y mostramos el primero
train_dict = df_train[categorical + numerical].to_dict(orient='records')
val_dict = df_val[categorical + numerical].to_dict(orient='records')
dict(sorted(train_dict[0].items()))

{'age': 74.0,
 'avg_glucose_level': 89.52,
 'bmi': 39.2,
 'ever_married': 'no',
 'gender': 'female',
 'heart_disease': 0,
 'hypertension': 0,
 'residence_type': 'urban',
 'smoking_status': 'unknown',
 'work_type': 'self-employed'}

In [48]:
from sklearn.feature_extraction import DictVectorizer
# Creamos el vectorizador y lo ajustamos a los datos de entrenamiento , esta tecnica es para hacer el one hot encoding
dv = DictVectorizer(sparse=False)
dv.fit(train_dict)


DictVectorizer(sparse=False)

In [49]:
# transformamos los datos a formato numérico
x_train = dv.transform(train_dict)
x_val = dv.transform(val_dict)
x_train[0]
x_val[0]

array([ 76.  , 207.96,  34.5 ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,
         1.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,
         0.  ,   0.  ,   0.  ,   1.  ])

In [50]:
# Podemos ver los nombres de las nuevas columnas generadas
dv.get_feature_names_out()

array(['age', 'avg_glucose_level', 'bmi', 'ever_married=no',
       'ever_married=yes', 'gender=female', 'gender=male',
       'heart_disease', 'hypertension', 'residence_type=rural',
       'residence_type=urban', 'smoking_status=formerly_smoked',
       'smoking_status=never_smoked', 'smoking_status=smokes',
       'smoking_status=unknown', 'work_type=children',
       'work_type=govt_job', 'work_type=never_worked',
       'work_type=private', 'work_type=self-employed'], dtype=object)

# 4. Entrenamiento de los modelos 

In [51]:
# Importamos los modelos y la matriz de confusión
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

## 4.1 Regresión logística

In [52]:
model_lr = LogisticRegression(solver='liblinear', random_state=1)
model_lr.fit(x_train, y_train)

LogisticRegression(random_state=1, solver='liblinear')

## 4.2 SVM

In [53]:
# Probamos inicialmente con un kernel lineal
model_svm = SVC(kernel='linear', probability=True, random_state=1)
model_svm.fit(x_train, y_train)

SVC(kernel='linear', probability=True, random_state=1)

## 4.3 Arbol de decición

In [54]:
model_dt = DecisionTreeClassifier(max_depth=5, random_state=1)
model_dt.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=1)

## Evaluación de modelos

In [58]:
def evaluar_modelo(nombre, modelo, x, y_real):
    # Predicción de etiquetas
    y_pred = modelo.predict(x)
    
    # Cálculo manual de la precisión (sin bibliotecas externas) [cite: 41]
    accuracy = (y_real == y_pred).mean()
    
    # Matriz de confusión [cite: 41]
    conf_mat = confusion_matrix(y_real, y_pred)
    
    print(f"{nombre}")
    print(f"Precisión (manual): {round(accuracy, 3)}")
    print("Matriz de Confusión:")
    print(conf_mat)

evaluar_modelo("Regresión Logística", model_lr, x_val, y_val)
evaluar_modelo("SVM", model_svm, x_val, y_val)
evaluar_modelo("Árbol de Decisión", model_dt, x_val, y_val)

Regresión Logística
Precisión (manual): 0.957
Matriz de Confusión:
[[1292    0]
 [  58    0]]
SVM
Precisión (manual): 0.957
Matriz de Confusión:
[[1292    0]
 [  58    0]]
Árbol de Decisión
Precisión (manual): 0.941
Matriz de Confusión:
[[1266   26]
 [  54    4]]


Los modelos base sufren de un gran desequilibrio. La Regresión Logística y la SVM inicial predecían siempre "no ictus", logrando un 95.7% de precisión pero siendo inútiles para detectar enfermos . Vamos a usar el gridsearh para encontrar algun modelo que logre conseguir mejores serultados

In [59]:
from sklearn.model_selection import GridSearchCV

# Definimos los parámetros a probar para la SVM
# añadimos el class_weight para balancear las clases
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf'],
    'class_weight': ['balanced'] 
}

In [60]:
# Configuramos la búsqueda. Usamos scoring='f1' o 'recall' para priorizar detectar los ictus
grid_svm = GridSearchCV(SVC(probability=True), param_grid, cv=3, scoring='f1')
grid_svm.fit(x_train, y_train)

GridSearchCV(cv=3, estimator=SVC(probability=True),
             param_grid={'C': [0.1, 1, 10], 'class_weight': ['balanced'],
                         'kernel': ['linear', 'rbf']},
             scoring='f1')

In [61]:
# Mostramos la mejor configuración encontrada
print(f"Mejores parámetros para SVM: {grid_svm.best_params_}")

Mejores parámetros para SVM: {'C': 1, 'class_weight': 'balanced', 'kernel': 'linear'}


In [62]:
# Evaluamos el mejor modelo encontrado
best_svm = grid_svm.best_estimator_
y_pred_best = best_svm.predict(x_val)

print(f"Nueva Precisión SVM: {round((y_val == y_pred_best).mean(), 3)}")
print("Nueva Matriz de Confusión:")
print(confusion_matrix(y_val, y_pred_best))

Nueva Precisión SVM: 0.724
Nueva Matriz de Confusión:
[[935 357]
 [ 15  43]]


Al aplicar GridSearch y pesos balanceados corregimos el subajuste inicial. Aunque la precisión bajó al 72.4% el modelo ahora detecta 43 pacientes en riesgo y reduce drásticamente los falsos negativos. Esta configuración es la mejor para el ámbito médico porque prioriza la detección real de la enfermedad sobre la simple precisión estadística. Para asegurarnos de tener el mejor modelo vamos a hacerlo tambien con la regresion logística y el arbol de decisión

In [67]:
# Definimos los parámetros a probar para la Regresión Logística
param_grid_lr = {
    'C': [0.01, 0.1, 1, 10],
    'solver': ['liblinear'],
    'class_weight': ['balanced']
}

grid_lr = GridSearchCV(LogisticRegression(max_iter=1000), param_grid_lr, cv=3, scoring='f1')
grid_lr.fit(x_train, y_train)

best_lr = grid_lr.best_estimator_
print(f"Mejores parámetros Regresión Logística: {grid_lr.best_params_}")

# Evaluamos el mejor modelo encontrado
y_pred_best_lr = best_lr.predict(x_val)
print(f"Nueva Precisión Regresión Logística: {round((y_val == y_pred_best_lr).mean(), 3)}")
print("Nueva Matriz de Confusión:")
print(confusion_matrix(y_val, y_pred_best_lr))

Mejores parámetros Regresión Logística: {'C': 10, 'class_weight': 'balanced', 'solver': 'liblinear'}
Nueva Precisión Regresión Logística: 0.746
Nueva Matriz de Confusión:
[[965 327]
 [ 16  42]]


In [66]:
# Definimos los parámetros a probar para el Árbol de Decisión
param_grid_dt = {
    'max_depth': [3, 5, 7, 10],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy'],
    'class_weight': ['balanced']
}

grid_dt = GridSearchCV(DecisionTreeClassifier(), param_grid_dt, cv=3, scoring='f1')
grid_dt.fit(x_train, y_train)

best_dt = grid_dt.best_estimator_
print(f"Mejores parámetros Árbol de Decisión: {grid_dt.best_params_}")

# Evaluamos el mejor modelo encontrado
y_pred_best_dt = best_dt.predict(x_val)
print(f"Nueva Precisión Árbol de Decisión: {round((y_val == y_pred_best_dt).mean(), 3)}")
print("Nueva Matriz de Confusión:")
print(confusion_matrix(y_val, y_pred_best_dt))

Mejores parámetros Árbol de Decisión: {'class_weight': 'balanced', 'criterion': 'gini', 'max_depth': 3, 'min_samples_split': 2}
Nueva Precisión Árbol de Decisión: 0.787
Nueva Matriz de Confusión:
[[1026  266]
 [  21   37]]


Ambos modelos logran equilibrar la detección, identificando 42 y 37 casos de ictus respectivamente. El Árbol de Decisión destaca por ofrecer la precisión más alta y el menor número de falsas alarmas, aunque es el que más casos reales deja sin detectar entre los tres modelos analizados.

El SVM es el modelo superior al detectar 43 casos positivos y minimizar los fallos a solo 15. Aunque su precisión sea ligeramente menor prioriza la seguridad del paciente al reducir drásticamente los falsos negativos.

# 5. Serialización del mejor modelo

In [69]:
import pickle


In [ ]:
with open('models/stroke-model.pck', 'wb') as f_out:
    pickle.dump((dv, best_svm), f_out)